---

- hosts: prod
  sudo: yes 

  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache Service 
    service: name=apache2 state=started 

  - name: Deploy Custom Index Page
    copy: src=templates/index.html dest=/var/www/html/abc.html 
